### ISSUE TITLE
Duplicate path

### ISSUE THREAD

**Issue by DQuest** [visi0nary/Elephone_P8000_manifest#1]
I have trouble with sync:

> fatal: duplicate path packages/apps/Snap in /home/.../.repo/manifest.xml

**Comment by janengelmohr** [comment]
That is odd. Do you have it in any other project already?

**Comment by DQuest** [comment]
Problem solved. Excuse for troubling =). It turns out , in the file "other.xml" was line:

> project path="packages/apps/Snap" name="android_packages_apps_Snap" revision="cm-13.0" remote="cm"

**Comment by janengelmohr** [comment]
No problem, good to hear that you figured it out!
